- hosts: all
  become: yes
  vars:
    tomcat_version: 10.1.12
    tomcat_install_dir: /opt/tomcat

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java 21
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Download Tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

    - name: Extract Tomcat
      unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes

    - name: Copy WAR file
      copy:
        src: "../target/myapp.war"
        dest: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/webapps/"

    - name: Start Tomcat
      shell: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/bin/startup.sh"
